# Identificación del proyecto en SonarCloud
sonar.projectKey=yulisg10-spec_ecommerce_lab
sonar.organization=yulisg10-spec

# Código fuente y tests
sonar.sources=lib
sonar.tests=test

# Archivos generados por build_runner — no tiene sentido analizarlos
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,lib/generated/**

# Reporte de cobertura generado por flutter test --coverage
sonar.dart.lcov.reportPaths=coverage/lcov.info